accounts/urls.py
from django.urls import path
from. import views


app_name ='accounts'
urlpatterns = [
    path('', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('404/', views.not_found, name='404'),

    
]

ehedvs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_users.urls')),
    path('accounts/', include('accounts.urls')),
    path('super_admin/', include('super_admin.urls')),
    path('registrar_admin/', include('registrar_admin.urls')),
    path('graduates/', include('graduates.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
     path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
      ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
          ),
          name='password_reset_confirm'),
     path('password-reset-complete/',
          auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

super_admin/urls.py
from django.urls import path
from . import views

app_name ='super_admin'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.registration, name='register'),
    path('univ/<str:id>/', views.institution_detail, name='univ'),
    path('account/', views.createAccount, name='account'),
    path('user_profile/', views.useProfile, name='user_profile'),
    path('update_unv/<int:pk>/',views.updateUnv, name='update_unv'),
    path('delete_unv/<int:pk>/',views.deleteUnv, name='delete_unv'),
    path('delete_user/<int:pk>/',views.deleteRegAdmin, name='delete_user'),
    path('activity_logs/', views.activity_logs, name='activity_logs'),
    path('view_request/', views.view_request, name='view_request'),
    path('delete_request/<int:id>/', views.delete_request, name='delete_request'),
    path('approve_request/<str:id>/',views.approve_request, name='approve_request'),
    path('message_ra/<str:id>/',views.message_with_registrar_admin, name='message_ra'),
    path('check/', views.checker, name='check')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from super_admin.models import University


class User(AbstractUser):
    is_registrar_admin = models.BooleanField(default=False)
    is_registrar_staff = models.BooleanField(default=False)
    image = models.ImageField(upload_to="user/", blank=True, null=True, default='user.png')


class RegistrarAdmin(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    university= models.OneToOneField(University, on_delete=models.CASCADE, null=True)
    

    

    def __str__(self):
        return str(self.user)

class RegistrarStaff(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    university = models.ForeignKey(University, on_delete=models.CASCADE, null=True)
    phone_number = models.CharField(max_length=20)
    
    
    def __str__(self):
       return str(self.user)

accounts/forms.py
from django.forms import ModelForm
from django.http import request
from .models import University
from accounts.models import User, RegistrarAdmin, RegistrarStaff
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import transaction
from django.contrib.auth.models import Group

        
class AdminSignUpForm(UserCreationForm):
    university = forms.ModelChoiceField(queryset=University.objects.all(), empty_label="Please select unversity")
    password1 = forms.CharField(
            label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(
            label='Confirm Password(again)', widget=forms.PasswordInput())

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['university','first_name','last_name','username', 'email' , 'password1', 'password2']
        help_texts = {
            'username': None,
            
        }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user. is_registrar_admin = True
        user.save()
        group = Group.objects.get(name='registrar_admin')
        user.groups.add(group)
        registrarAdmin = RegistrarAdmin.objects.create(user=user)
        registrarAdmin.university=self.cleaned_data.get('university')
        registrarAdmin.save()
        return user




class StaffSignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        self._loged_user=kwargs.pop('loged_user', None)
        super().__init__(*args, **kwargs)
    #university = forms.ModelChoiceField(queryset=University.objects.all(), empty_label="Please select your unversity")
    #university = forms.CharField(max_length=200)
    password1 = forms.CharField(
            label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(
            label='Confirm Password(again)', widget=forms.PasswordInput())

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name','last_name','username', 'email' , 'password1', 'password2']
        help_texts = {
            'username': None,
            
        }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user. is_registrar_staff = True
        user.save()
        group = Group.objects.get(name='registrar_staff')
        user.groups.add(group)
        
       
        #univ = RegistrarAdmin.objects.get(user_id=userId)
        registrarStaff = RegistrarStaff.objects.create(user=user)
        #userId=request.user
        #registrarStaff.university=self.cleaned_data.get('university')
        registrarStaff.university_id=self._loged_user
        #userId=self._loged_user

        registrarStaff.save()
        #print(userId)
        return user
 

super_admin/forms.py
from django.forms import ModelForm
from .models import University

class UniversityForm(ModelForm):
    class Meta:
        model=University
        fields='__all__'
        labels = {
        'pob':'Post Box Office',
        'phone_no1': 'Phone number 1',
        'phone_no2': 'Phone number 2',
        'fax_no':'Fax number',
        'website':'Website address'
        }

accounts/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages

#login 
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_superuser:
                login(request, user)
                return redirect('/super_admin/')
        elif user is not None and user.is_registrar_admin:
                login(request, user)
                return redirect('/registrar_admin/')
        elif user is not None and user.is_registrar_staff:
                login(request, user)
                return redirect('/graduates/')
        else:
            messages.info( request,'username or password is incorrect')
    return render(request, 'accounts/login.html')

#logout
def logout_page(request):
    logout(request)
    return redirect('accounts:login')


def not_found(request):
    return render(request, 'accounts/404.html')

super_admin/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from super_admin.models import University, ActivityLog
from accounts.models import RegistrarAdmin, RegistrarStaff, User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from accounts.forms import AdminSignUpForm
from django.contrib.auth.decorators import login_required
from .forms import UniversityForm
from accounts.decorators import registrar_admin, registrar_staff, super_admin
from registrar_admin.models import Request, Faculty
from graduates.models import Student
from django.contrib.auth import get_user_model
from django.db import IntegrityError

from background_task import background
from background_task.models import CompletedTask
import subprocess
import shlex






#dashboar on super admin page
@login_required(login_url='accounts:login')
@super_admin
def dashboard(request):
    lists = University.objects.all().order_by('-id')
    total_unv = lists.count()
    registrar_admin = RegistrarAdmin.objects.all().count()
    registrar_staff = RegistrarStaff.objects.all().count()
    users=registrar_admin+registrar_staff
    activities = ActivityLog.objects.all()
    user_creation = ActivityLog.objects.filter(operation="create_staff").count()
    
    student_registry = ActivityLog.objects.filter(operation="student_registry").count()

    certificate_generation = ActivityLog.objects.filter(operation="student_deletion").count()
  
    student_deletion = ActivityLog.objects.filter(operation="certificate_generation").count()
 
    context = {
         'activities':activities,
        'lists':lists ,
         'total_unv':total_unv,
          'users':users,
          'student_registry': student_registry, 
          'certificate_generation': certificate_generation,
          'student_deletion':student_deletion,
          'user_creation':user_creation

          
          }
    return render(request, 'super_admin/dashboard.html', context)

    # lists = University.objects.all().order_by('-id')
    # students=Student.objects.filter(level_of_completion=100.0).count()
    # total_unv = lists.count()
    # registrar_admin = RegistrarAdmin.objects.all().count()
    # registrar_staff = RegistrarStaff.objects.all().count()
    # users=registrar_admin+registrar_staff
    # context = {'lists':lists , 'total_unv':total_unv, 'users':users, 'students':students}
    # return render(request, 'super_admin/dashboard.html', context)

# register high educational institution
@login_required(login_url='accounts:login')
@super_admin
def registration(request):
    form = UniversityForm()
    if request.method=='POST':
        form = UniversityForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/super_admin/')
    context = {'form':form}
    return render(request, 'super_admin/register.html', context)



#create account for registrar admin
@login_required(login_url='accounts:login')
@super_admin
def createAccount(request):
    form = AdminSignUpForm()
    if request.method=='POST':
        try:
            form = AdminSignUpForm(request.POST)
            if form.is_valid():
                form.save()
                print(request.POST['university'])
                return redirect('/super_admin/user_profile')
            else:
                 messages.warning(request,'the two password doesnot match')
           
 
        except IntegrityError as e:
            if 'UNIQUE constraint' in str(e.args):
                #return redirect('/accounts/exist/')
                messages.warning(request,'University you have selected has got ADIMN already')
               
        
    context = {'form': form}
    return render(request, 'super_admin/account.html', context)

#user profile
@login_required(login_url='accounts:login')
@super_admin
def useProfile(request):
    lists = RegistrarAdmin.objects.all().order_by('-user_id')[:6]
    context = {'lists':lists}
    return render(request, 'super_admin/user_profile.html', context)


#institution detail
def institution_detail(request, id):
    institution = University.objects.get(id=id)
    registrar_staffs = RegistrarStaff.objects.filter(university=institution).count()
    students = Student.objects.filter(institution=institution).count()
    recent_activites = ActivityLog.objects.filter(institution=institution)[:3]
    certificate_generated = ActivityLog.objects.filter(operation="certificate_generation", institution=institution).count()
    
    schools = Faculty.objects.filter(university=institution)[:4]

    try:
        registrar_admin=RegistrarAdmin.objects.get(university=institution)
        registrar_staffs=registrar_staffs+1
    
    except RegistrarAdmin.DoesNotExist:
        registrar_admin="No Admin"
    

    context = {
         'institution':institution,
         'registrar_admin':registrar_admin,
         'registrar_staffs':registrar_staffs,
         'students':students,
         'recent_activites':recent_activites,
         'certificate_generated': certificate_generated,
         'schools':schools
    }
    return render(request, 'super_admin/university.html', context)

#update univeristy
@login_required(login_url='accounts:login')
@super_admin
def updateUnv(request, pk):
    univ = University.objects.get(id=pk)
    form = UniversityForm(instance=univ)
    if request.method=='POST':
        form = UniversityForm(request.POST, instance=univ)
        if form.is_valid():
            form.save()
            return redirect('/super_admin/')
    context = {'form':form}
    return render(request, 'super_admin/register.html', context)

#delete University
@login_required(login_url='accounts:login')
@super_admin
def deleteUnv(request, pk ):
    univ = University.objects.get(id=pk)
    univ.delete()
    return redirect("/super_admin/")

#delet Registrar_admin
@login_required(login_url='accounts:login')
@super_admin
def deleteRegAdmin(request, pk):
    user = User.objects.get(id=pk)
    user.delete()
    return redirect("/super_admin/user_profile/")

#activity logs
@login_required(login_url='accounts:login')
@super_admin
def activity_logs(request):
    activities = ActivityLog.objects.all()
    user_creation = ActivityLog.objects.filter(operation="create_staff").count()
    student_registry = ActivityLog.objects.filter(operation="student_registry").count()
    certificate_generation = ActivityLog.objects.filter(operation="student_deletion").count()
    student_deletion = ActivityLog.objects.filter(operation="certificate_generation").count()
    context = {

       'activities':activities,
       'user_creation':user_creation,
       'student_registry':student_registry,
       'certificate_generation': certificate_generation,
       'student_deletion':student_deletion,
    }
    return render(request, 'super_admin/activiy_logs.html', context)


# view send request
def view_request(request):
    logged_user=request.user
    subjects = Request.objects.exclude(sender=logged_user)[0:5]
    context = {
        'subjects':subjects
    }
    return render(request, 'super_admin/view_request.html', context)

#chat with specific user
def message_with_registrar_admin(request, id):
    registrar_admin = User.objects.get(id=id)
    super_admin = get_user_model().objects.get(is_superuser=True)
    last_message = Request.objects.filter(sender=registrar_admin).first()
    messages_sent = Request.objects.filter(sender=super_admin, reciever=registrar_admin)[0:1]
    top_four_messages = Request.objects.filter(sender=super_admin, reciever=registrar_admin )[0:4]
    print(last_message)
    if request.method =='POST':
        subject = request.POST.get('subject')
        Request.objects.create(sender=super_admin, reciever=registrar_admin, request=subject)
    
    
    context = {
     'registrar_admin':registrar_admin,
     'last_message': last_message ,
     'registrar_admin':registrar_admin,
     'messages_sent':messages_sent,
     'super_admin': super_admin,
     'top_four_messages':top_four_messages
    }
    return render(request, 'super_admin/message_with_ra.html', context)
# approving request
def approve_request(request, id):
    subject = Request.objects.get(id=id)
    if request.method == 'POST':
        Request.objects.filter(id=id).update(status="approved")
        CompletedTask.objects.all().delete()
        process_tasks()
        expire_request(pk=id)
        return redirect('/super_admin/view_request')
    context = {'subject':subject}
    return render(request, 'super_admin/approve_request.html', context)

def delete_request(request, id):
    rqst = Request.objects.get(id=id)
    rqst.delete()
    return redirect('/super_admin/user_profile/')

#------------background task expring request-------#   
@background(schedule=30)
def expire_request(pk):
    Request.objects.filter(id=pk).update(status="expired")
   

# running process tasks background
def process_tasks():
    process_tasks_cmd = "python manage.py process_tasks"
    process_tasks_ags = shlex.split(process_tasks_cmd)
    process_tasks_subprocess = subprocess.Popen(process_tasks_ags)

# request expired checker
def checker(request):
    req = Request.objects.all().first()
    if req:
        status = req.status

    else:
        status = 'none'

    
    return HttpResponse(status)

templates/super_admin/approve_request.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-HECAS|request_approve</title>
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.min.css ' %}">
</head>
<body>
    <div class="container mt-4 ">
    <div class="col-md-5  ">
    <p>Do you want this request to be approved ?</p>
    <form action="{% url 'super_admin:approve_request' subject.id %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'super_admin:view_request' %}" class="btn btn-lg btn-info ml-2">Cancel</a>
        <input type="submit" name='delete' value="Yes" class="btn btn-lg btn-danger ">

    </form>
    </div>
</div>
</body>
</html>

templates/super_admin/dashboard.html
        {% extends 'super_admin/main.html' %}
        {% load static %}
        {% block subtitle %}Dashboard{% endblock %}
        {% block first %}home {% endblock %}
        {% block second %}dashboard{% endblock %}
 
       {% block content%}
<div class="row">
<div class="col-md-6">
<canvas id="myChart" width="400" height="200"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
type: 'bar',
data: {
 labels: ['Registared Institution', 'System Users', 'Generated certificate', 'page views'],
 datasets: [{
     label: '# Dashboard',
     data: [{{total_unv}}, {{users}}, 3, 5],
     backgroundColor: [
         'rgba(255, 99, 132, 1)',
         'rgba(54, 162, 235, 1)',
         'rgba(255, 206, 86, 1)',
         'rgba(75, 192, 192, 1)',
         'rgba(153, 102, 255, 1)',
         'rgba(255, 159, 64, 1)'
     ],
     borderColor: [
         'rgba(255, 99, 132, 1)',
         'rgba(54, 162, 235, 1)',
         'rgba(255, 206, 86, 1)',
         'rgba(75, 192, 192, 1)',
         'rgba(153, 102, 255, 1)',
         'rgba(255, 159, 64, 1)'
     ],
     borderWidth: 1
 }]
},
options: {
 scales: {
     y: {
         beginAtZero: true
     }
 }
}
});
</script>
</div>

<div class="col-md-6">
<canvas id="myChart1" width="400" height="200"></canvas>
<script>
var ctx1 = document.getElementById('myChart1').getContext('2d');
var myChart1 = new Chart(ctx1, {
type: 'line',
data: {
 labels: ['user_created', 'student_registry', 'certificate_generation', 'student_deletion'],
 datasets: [{
     label: '# Activity logs',
     data: [{{user_creation}}, {{student_registry}}, {{certificate_generation}}, {{student_deletion}}],
     backgroundColor: [
         'rgba(255, 99, 132, 1)',
         'rgba(54, 162, 235, 1)',
         'rgba(255, 206, 86, 1)',
         'rgba(75, 192, 192, 1)',
         'rgba(153, 102, 255, 1)',
         'rgba(255, 159, 64, 1)'
     ],
     borderColor: [
         'rgba(255, 99, 132, 1)',
         'rgba(54, 162, 235, 1)',
         'rgba(255, 206, 86, 1)',
         'rgba(75, 192, 192, 1)',
         'rgba(153, 102, 255, 1)',
         'rgba(255, 159, 64, 1)'
     ],
     borderWidth: 1
 }]
},
options: {
 scales: {
     y: {
         beginAtZero: true
     }
 }
}
});
</script>
</div>

</div>


        <div class="row mt-5">
          <div class="col-12">
            <h4 class="text-center mb-3"><b>List of Institutions </b></h4>
              <div class="card-header callout callout-success ">
                <div class="">

                <h3 class="card-title">List of Registered Institutions </h3>
                </div>
                <div class="card-tools float-right">
                  <a  type="submit" class="btn  btn-outline-success btn-xs mr-5 text-xs " href="{% url 'super_admin:register' %}" >
                    <i class="fas fa-plus-circle"> Add new</i>
                  </a>
                </div>
                </div>
              <!-- /.card-header -->
   
              

              <div class="card-body table-responsive px-0">
                <table class="table table-hover text-nowrap table-light">
                  <thead  >
                    <tr>
                      <th>Logo</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Phone no</th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for list in lists %}
                    <tr >
                      <td > <a href="{% url 'super_admin:univ' list.id%}"><img class="img-size-50 mr-3 img-circle" src="{{list.logo.url}}" alt=""></a> </td>
                      <td>{{list.name}}</td>
                      <td>{{list.email}}</td>
                      <td>{{list.phone_no1}}</td>
                      <td>
                        <a href="{% url 'super_admin:update_unv' list.id %}" class="btn text-secondary px-0 "><i class="fas fa-pencil-alt  "></i></a>
                      </td>
                     <td>
                       <a href="#" onclick="deletingUniversty({{list.id}})" class="btn text-danger px-0 "><i class="fas fa-trash-alt "></i></a>
                     </td>
                    </tr>
                    {% endfor %}
                   
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        
        
        {% endblock %}      


        {% block javascript %}

        <script>
          function deletingUniversty(id){
           Swal.fire({
             "title":"Are you sure",
             "text":"You want to delete this University ",
             "icon":"question",
             "showCancelButton":true,
             "cancelButtonText":"No, Cancel",
             "confirmButtonText":"Yes, Delete",
             "reverseButtons":true,
             "confirmButtonColor":"#dc3545",
             "cancelButtonColor":"#17a2b8",
             "width":330,
             "height":70,


           })
           .then(function(result) {
             if (result.isConfirmed){
               window.location.href="/super_admin/delete_unv/"+id+"/"
             }
           })
          }
        
          
        
        </script> 
        
        {% endblock %}      

templates/super_admin/delete_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-HEDVS|delete</title>
    <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/e-hedvs.min.css ' %}">
    


</head>
<body>

    <div class="container mt-4">
        <h5>Are you sure you want to delete <strong>{{user}} </strong>?</h5>
        
        <form action="{% url 'super_admin:delete_user' user.id %}" method="POST" >
            {% csrf_token %}
            <a href="{% url 'super_admin:user_profile' %}" class="btn btn-lg btn-info ml-2">Cancel</a>
            <input type="submit" name='delete' value="Yes" class="btn btn-lg btn-danger ">
    
        </form>
     </div> 

             
            <!-- REQUIRED SCRIPTS -->



<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- e-HEDVS App -->
<script src=" {% static 'dist/js/e-hedvs.min.js' %}"></script>

</body>
</html>

templates/super_admin/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-light navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
    
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">5</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">5 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 2 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
     <!---User dropdown menu-->
   
     <li class="nav-item dropdown user-menu">
      <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
        <img src="{% static 'dist/img/default.png' %}" class="user-image img-circle elevation-2" alt="User Image">
        <span class="d-none d-md-inline text-capitalize text-gray-dark">{{request.user}}</span>
      </a>
      <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <!-- User image -->
        <li class="user-header bg-default">
          <img src="{% static 'dist/img/1.jpg' %}" class="img-circle elevation-2" alt="User Image">

          <p class="text-capitalize ">
            <span class="text-purple">{{request.user}}</span>
           
            <small> <strong>Member Since </strong>  {{request.user.date_joined|date:"F d,Y"}}</small>
          </p>
          <div class="dropdown-divider m-0"></div>
        </li>
        <!-- Menu Body -->
          <li class="text-center mb-1 hover" ><a href="#" class="text-secondary"><i class="fa fa-user mr-2 mb-1 text-purple"></i>Profile</a></li>
          <li class="text-center mb-1"><a href="{% url 'accounts:logout' %}" class="text-secondary"><i class="fa fa-sign-out-alt mr-2 text-purple" ></i>logout</a></li>
          <li class="text-center mb-1 hover"><a href="#!" class="text-secondary"><i class="fa fa-cog mr-2 text-purple"></i>Setting</a></li>
          <li class="p-0">
             <div class="dropdown-divider m-0"></div>
        <br>
      </ul>
    </li>
    </ul>
  </nav>

templates/super_admin/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4 ">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'dist/img/ehedvs.jpg' %}"
       alt="e-HECAS Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light"><b class="text-primary">e</b>-HEDVS</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{request.user.image.url}}" class="img-circle elevation-1 bg-success p-1" alt="User Image">
        </div>
        <div class="info text-capitalize">
          <a href="#" class="d-block text-info">{{request.user}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
       
          <li class="nav-item">
            <a href="{% url 'super_admin:dashboard' %}" class="nav-link {% block active %}{% endblock %}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          
          
          <li class="nav-item">
            <a href="{% url 'super_admin:register' %}" class="nav-link " >
              <i class="nav-icon fas fa-school"></i>
              <p>
                Institution Registration
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            <a href="{% url 'super_admin:account' %}" class="nav-link ">
              <i class="nav-icon fas fa-user-circle"></i>
              <p>
               Grant Account
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'super_admin:user_profile' %}" class="nav-link ">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Users Profile
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'super_admin:activity_logs' %}" class="nav-link ">
              <i class="nav-icon fa fa-blog"></i>
              <p>
                View activity logs
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'super_admin:view_request' %}" class="nav-link ">
              <i class="nav-icon fa fa-envelope-open-text"></i>
              <p>
               View Request
              </p>
            </a>
          </li>
          

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>