accounts/urls.py
from django.urls import path
from. import views


app_name ='accounts'
urlpatterns = [
    path('', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('404/', views.not_found, name='404'),

    
]

ehedvs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_users.urls')),
    path('accounts/', include('accounts.urls')),
    path('super_admin/', include('super_admin.urls')),
    path('registrar_admin/', include('registrar_admin.urls')),
    path('graduates/', include('graduates.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
     path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
      ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
          ),
          name='password_reset_confirm'),
     path('password-reset-complete/',
          auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

registrar_admin/urls.py
from django.urls import path
from.import views
app_name = 'registrar_admin'
urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('faculty/',views.faculty, name='faculty'),
    path('program/', views.program, name='program'),
    path('delete_faculty/<str:id>/',views.delete_faculty, name='delete_faculty'),
    path('update_faculty/<str:id>/',views.update_faculty, name='update_faculty'),
    path('update_program/<str:id>/',views.update_program, name='update_program'),
    path('delete_program/<str:id>/',views.delete_program, name='delete_program'),
    path('account/', views.createAccount, name='account'),
    path('user_profile/', views.useProfile, name='user_profile'),
    path('delete_staff/<str:id>/',views.deleteRegStaff, name='delete_staff'),
    path('send_request/', views.send_request, name='send_request'),
    path('delete_request/<int:id>/', views.delete_request, name='delete_request'),
    path('activity_logs/', views.activity_logs, name='activity_logs'),
    path('certificate_archive/', views.certificate_archive, name='certificate_archive'),
    path('status_detail/<path:id>/', views.status_detail, name='status_detail' ),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from super_admin.models import University


class User(AbstractUser):
    is_registrar_admin = models.BooleanField(default=False)
    is_registrar_staff = models.BooleanField(default=False)
    image = models.ImageField(upload_to="user/", blank=True, null=True, default='user.png')


class RegistrarAdmin(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    university= models.OneToOneField(University, on_delete=models.CASCADE, null=True)
    

    

    def __str__(self):
        return str(self.user)

class RegistrarStaff(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    university = models.ForeignKey(University, on_delete=models.CASCADE, null=True)
    phone_number = models.CharField(max_length=20)
    
    
    def __str__(self):
       return str(self.user)

graduates/models.py
from typing import Tuple
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from super_admin.models import University
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw
from accounts.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save
from django.dispatch import receiver
from registrar_admin.models import Faculty, Program


#from ehedvs import settings


class Student(models.Model):
    institution = models.ForeignKey(
        University, on_delete=models.CASCADE, null=True)
    id = models.CharField(max_length=200, primary_key=True,
                          verbose_name='ID Number ')
    full_name = models.CharField(max_length=255, verbose_name='student name')
    gender = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField()
    registration_year = models.DateField(
        auto_now_add=True, null=True, verbose_name='Registration_Date')
    created_by = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL, null=True)
    school = models.ForeignKey(
        Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    department = models.ForeignKey(
        Program, on_delete=models.SET_NULL, null=True, blank=True)
    level_of_completion = models.FloatField(default=0.0, blank=True, null=True)

    class Meta:
        ordering = ['-registration_year']

    def __str__(self):
        return self.full_name


def academic_status_determiner(batch, semester, GPA, CGPA):
    if batch == 1 and semester == 1:
        if GPA >= 1.50 and CGPA >= 1.50:
            status = "Promoted"
        else:
            status = "Dismissed"
    elif batch == 1 and semester == 2:
        if GPA < 1.50 or CGPA < 1.75:
            status = "Dismissed"
        else:
            status = "Promoted"

    elif batch >=2:
        if GPA<1.50 or CGPA < 1.75:
            status = "Dismissed"
        else:
            status = "Promoted"


    
    else:
        status = "Dismissed"

    return status


class AcademicHistory(models.Model):
    sem = (
        ('1', '1st semester'),
        ('2', '2nd semester'),
    )
    status = (
        ('Promoted', 'Promoted'),
        ('Dismissed', 'Dismissed'),
        ('suspended', 'suspended')
    )
    batch = (
        ('1', '1st year'),
        ('2', '2nd year'),
        ('3', '3rd year'),
        ('4', '4th year'),
        ('5', '5th year'),
        ('6', '6th year'),
    )

    student = models.ForeignKey(Student,  on_delete=models.CASCADE)
    batch = models.CharField(
        max_length=20, choices=batch, verbose_name="Class Year")
    semester = models.CharField(max_length=20, choices=sem)
    GPA = models.FloatField(default=0.0)
    CGPA = models.FloatField(default=0.0)
    academic_status = models.CharField(
        max_length=20, choices=status, blank=True, null=True)
    uploaded_by = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL, null=True)
    uploaded_date = models.DateField(auto_now=True, verbose_name='Date')

    class Meta:
        ordering = ['-uploaded_date']

    def __str__(self):
        return "%s 's  %s year %s semester Academical status " % (self.student, self.batch, self.semester)


@receiver(pre_save, sender=AcademicHistory)
def accademical_status(sender, instance, *args, **kwargs):
    instance.academic_status = academic_status_determiner(
        instance.batch, instance.semester, instance.GPA, instance.CGPA)


class Profile(models.Model):
    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    qr_code = models.ImageField(upload_to='qr_codes')
    image = models.ImageField(default='default.png', upload_to='student_image')

    def __str__(self):
        return f'{self.student} Profile'


# pre_save signal for generating  qr_code

@receiver(pre_save, sender=Profile)
def profile_pre_save(sender, instance, *args, **kwargs):
    if not instance.qr_code:
        qrcode_img = qrcode.make(instance.student.id)
        canvas = Image.new('RGB', (320, 320), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qr_code-{instance.student.id}.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        instance.qr_code.save(fname, File(buffer), save=False)
        canvas.close()



 

registrar_admin/models.py
from django.db import models
from super_admin.models import University
from django.conf import settings
from accounts.models import RegistrarAdmin
User = settings.AUTH_USER_MODEL

from .validators import validate_even




class Faculty(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    total_programs = models.PositiveSmallIntegerField()

    class Meta:
        unique_together = ('university', 'name',)
        ordering = ['-id']

    def __str__(self):
        return self.name

  


class Program(models.Model):
    degree_type =(
        (
           'BA','Bachelor of  Art',
        ),
        (
            'BSc','Bachelor of Science'
        ),
        (
           'BEd','Bachelor of Education'
        ),
        (
            'MD','Doctor of Medicine'
        ),
        (
            'BPh', 'Bachelor of Philosophy'
        ),

    )
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)
    year_required = models.PositiveSmallIntegerField(validators=[validate_even])
    degree_type = models.CharField(max_length=50, choices=degree_type)

    def __str__(self):
        return self.name


# request db

class Request(models.Model):
    request_status =(
        ('pending','pending'),
        ('approved','approved'),
        ('expired','expired'),
    )
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="registrar_admin")
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name="super_admin")
    request = models.TextField()
    status = models.CharField(max_length=50, choices=request_status, default='pending')
    timestamp = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.request
    

accounts/forms.py
from django.forms import ModelForm
from django.http import request
from .models import University
from accounts.models import User, RegistrarAdmin, RegistrarStaff
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import transaction
from django.contrib.auth.models import Group

        
class AdminSignUpForm(UserCreationForm):
    university = forms.ModelChoiceField(queryset=University.objects.all(), empty_label="Please select unversity")
    password1 = forms.CharField(
            label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(
            label='Confirm Password(again)', widget=forms.PasswordInput())

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['university','first_name','last_name','username', 'email' , 'password1', 'password2']
        help_texts = {
            'username': None,
            
        }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user. is_registrar_admin = True
        user.save()
        group = Group.objects.get(name='registrar_admin')
        user.groups.add(group)
        registrarAdmin = RegistrarAdmin.objects.create(user=user)
        registrarAdmin.university=self.cleaned_data.get('university')
        registrarAdmin.save()
        return user




class StaffSignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        self._loged_user=kwargs.pop('loged_user', None)
        super().__init__(*args, **kwargs)
    #university = forms.ModelChoiceField(queryset=University.objects.all(), empty_label="Please select your unversity")
    #university = forms.CharField(max_length=200)
    password1 = forms.CharField(
            label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(
            label='Confirm Password(again)', widget=forms.PasswordInput())

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name','last_name','username', 'email' , 'password1', 'password2']
        help_texts = {
            'username': None,
            
        }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user. is_registrar_staff = True
        user.save()
        group = Group.objects.get(name='registrar_staff')
        user.groups.add(group)
        
       
        #univ = RegistrarAdmin.objects.get(user_id=userId)
        registrarStaff = RegistrarStaff.objects.create(user=user)
        #userId=request.user
        #registrarStaff.university=self.cleaned_data.get('university')
        registrarStaff.university_id=self._loged_user
        #userId=self._loged_user

        registrarStaff.save()
        #print(userId)
        return user
 

registrar_admin/forms.py
from django import forms
from super_admin.models import University
from django.forms import ModelForm
from .models import Faculty, Program
from django.db import transaction
class FacultyForms(ModelForm):
    def __init__(self, *args, **kwargs):
        self._loged_user=kwargs.pop('loged_user', None)
        super().__init__(*args, **kwargs)
       
    #university = forms.CharField(max_length=300)
    

    class Meta:
        model=Faculty
        fields=['name', 'total_programs']
        labels = {
        'name':'Name of faculty',
        
        }
    def save(self):
        school = super().save(commit=False)
        fclt = Faculty.objects.create(university=self._loged_user ,
         name=school, total_programs=school.total_programs)


    

class ProgramForms(ModelForm):
    class Meta:
        model=Program
        fields='__all__'
        labels = {
        'name':'Name of program',
        
        }
        
    def __init__(self, logged_univ, *args, **kwargs):
        super(ProgramForms, self).__init__(*args,**kwargs)
        self.fields['faculty'].queryset=Faculty.objects.filter(university=logged_univ)

accounts/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages

#login 
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_superuser:
                login(request, user)
                return redirect('/super_admin/')
        elif user is not None and user.is_registrar_admin:
                login(request, user)
                return redirect('/registrar_admin/')
        elif user is not None and user.is_registrar_staff:
                login(request, user)
                return redirect('/graduates/')
        else:
            messages.info( request,'username or password is incorrect')
    return render(request, 'accounts/login.html')

#logout
def logout_page(request):
    logout(request)
    return redirect('accounts:login')


def not_found(request):
    return render(request, 'accounts/404.html')

templates/registrar_admin/account.html
        {% extends 'registrar_admin/main.html' %}
        {% load static %}
        {% load crispy_forms_tags %}
        {% block subtitle %}Account{% endblock %}
        {% block first %}home {% endblock %}
        {% block second %}account{% endblock %}
 
       {% block content%}
  
       <div class="row ml-5">
        <div class="col-lg-9">
            <div class="register">
                <div class="register-logo">
                  <b style="font-family: Source;">Create Account for Registerar Staff</b>
                </div>
              
                <div class="card ">
                  <div class="card-body register-card-body">
               
                    <form action="" method="POST">
                      {% csrf_token %}

                      <div class="row">
                        <div class="col-md-6">
                            {{form.first_name|as_crispy_field}} 
                        </div>
                        <div class="col-md-6">
                          {{form.last_name|as_crispy_field}} 
                      </div>
                        
                       </div>

                       <div class="row">
                       
                        <div class="col-md-6">
                          {{form.username|as_crispy_field}}
                      </div>
                        <div class="col-md-6">
                          {{form.email|as_crispy_field}}
                      </div>
                       
                       </div>
                      
                          <div class="row ">
                            <div class="col-md-4">
                              {{form.password1|as_crispy_field}}
                          </div>
                            <div class="col-md-4">
                              {{form.password2|as_crispy_field}} 
                             </div>
                            <div class="col-md-4" style="margin-top: 30px;">
                              <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-database"></i>&nbsp;  Register</button>
                            </div>
                        
                      </div>
                    </form>
                   
                  </div>
                  <!-- /.form-box -->
                </div><!-- /.card -->
              </div>

        </div>
       </div>

      {% endblock %}
      

templates/registrar_admin/certificate_archive.html
{% extends 'registrar_admin/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block subtitle %}Certificate Archive{% endblock %}
{% block first %}Home {% endblock %}
{% block second %}Archive{% endblock %}
{% block content%}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header border-0">
              <h3 class="card-title mb-1"> <i class="fa fa-print text-orange mr-1"></i>
              <span style=" font-style: oblique; ,font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">Certificate</span></h3>
              <div class="card-tools">
                <a >
                <i class="fas fa-barcode  text-indigo" ></i>
                </a>
              </div>
            </div>
            <div class="card-body table-responsive p-3">
              <table class="table table-striped table-valign-middle certificate table-borderless">
                <thead>
                <tr>
                  <th>Image</th>
                  <th>Student</th>
                  <th>ID</th>
                  <th>Department</th>
                  <th>Batch</th>
                  <th>More</th>
        
                </tr>
                </thead>
                <tbody>
                    {% for certificate in certificates %}
                <tr>
                  <td>
                    <img src="{{certificate.profile.image.url}}" alt="student image" class="img-circle img-size-32 mr-2">
                  </td>
                  <td>{{certificate}}</td>
                  <td>{{certificate.id}}</td>
                  <td>{{certificate.department}}</td>
                  <td>
                    <small class="text-success mr-1">
                      
                   {{certificate.registration_year.year}}
                  </td>
                  <td>
                    <a href="{% url 'registrar_admin:status_detail' certificate.id %}"><i class="fa fa-angle-double-right"></i></a>
                  </td>
                 
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
    </div>

</div>
 
 
  
{% endblock %}

{% block javascript %}
<script>
    $('.certificate').DataTable({
         ordering:false,
        lengthMenu:[[3,10,15,50,-1],[3,10,15,50,"All"]],
       
    });
</script>
{% endblock %} 

templates/registrar_admin/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-light navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
<!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">5</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">5 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 2 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
          <img src="{% static 'dist/img/default.png' %}" class="user-image img-circle elevation-2" alt="User Image">
          <span class="d-none d-md-inline text-capitalize">{{request.user}}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- User image -->
          <li class="user-header bg-default">
            <img src="{% static 'dist/img/1.jpg' %}" class="img-circle elevation-2" alt="User Image">
  
            <p class="text-capitalize ">
              <span class="text-purple">{{request.user}}</span>
             
              <small> <strong>Member Since </strong>  {{request.user.date_joined|date:"F d,Y"}}</small>
            </p>
            <div class="dropdown-divider m-0"></div>
          </li>
          <!-- Menu Body -->
            <li class="text-center mb-1 hover" ><a href="#" class="text-secondary"><i class="fa fa-user mr-2 mb-1 text-purple"></i>Profile</a></li>
            <li class="text-center mb-1"><a href="{% url 'accounts:logout' %}" class="text-secondary"><i class="fa fa-sign-out-alt mr-2 text-purple" ></i>logout</a></li>
            <li class="text-center mb-1 hover"><a href="#!" class="text-secondary"><i class="fa fa-cog mr-2 text-purple"></i>Setting</a></li>
            <li class="p-0">
               <div class="dropdown-divider m-0"></div>
          <br>
        </ul>
      </li>
     
    </ul>
  </nav>

templates/registrar_admin/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'dist/img/ehedvs.jpg' %}"
       alt="e-HECAS Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light"><b class="text-primary">e</b>-HEDVS</span>
     </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{request.user.image.url}}" class="img-circle elevation-1 bg-success p-1" alt="User Image">
        </div>
        <div class="info text-capitalize">
          <a href="#" class="d-block"> {{request.user}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
       
          <li class="nav-item">
            <a href="{% url 'registrar_admin:dashboard' %}" class="nav-link {% block active %}{% endblock %}">
                <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          
          <li class="nav-item ">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-school"></i>
              <p >
               College
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'registrar_admin:faculty' %}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p class="text-info">Faculties</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'registrar_admin:program'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p class="text-info">Programs</p>
                </a>
              </li>
            </ul>
        </li>
       
          <li class="nav-item">
            <a href="{% url 'registrar_admin:account' %}" class="nav-link " >
              <i class="nav-icon fas fa-user-friends"></i>
              <p>
                Register Staff
              </p>
            </a>
          </li>
        

          <li class="nav-item">
            <a href="{% url 'registrar_admin:user_profile' %}" class="nav-link ">
              <i class="nav-icon fas fa-user-secret"></i>
              <p>
                User Profile
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'registrar_admin:activity_logs' %}" class="nav-link ">
              <i class="nav-icon fa fa-sitemap"></i>
              <p>
                Activity Logs
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'registrar_admin:certificate_archive' %}" class="nav-link ">
              <i class="nav-icon fa fa-print"></i>
              <p>
                Certificate Archive
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'registrar_admin:send_request' %}" class="nav-link ">
              <i class="nav-icon fa fa-question-circle"></i>
              <p>
               Send Request
              </p>
            </a>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/registrar_admin/status_detail.html
{% extends 'registrar_admin/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block subtitle %}Detail Academical Status {% endblock %}
{% block first %}Home {% endblock %}
{% block second %}Academical Status{% endblock %}
{% block content%}

<div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><span class="text-info">{{name}}</span>'s Academical status</h3>
       {% if name.level_of_completion == 100.0 %}
       <p class="float-right text-success"> <i class="fa fa-hand-paper"></i> has completed</p>
       {% else %}
       <p class="float-right text-warning"> <i class="fa fa-door-open"></i> Not yet completed </p>
       {% endif %}
      </div>
      <div class="card-body p-0">
        <table class="table table-striped ">
          <thead>
            <tr>
              <th>Batch</th>
              <th>Semester</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
              {% for student in students %}
            <tr>
              <td>{{student.get_batch_display}}</td>
             <td>{{student.get_semester_display}}</td>
             <td>
               {% if student.academic_status == "failed" %}
               <span class="text-danger">{{student.academic_status}}</span>
               {% else %}
               {{student.academic_status}}
               {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="card-footer bg-white">
        <div class="row border-top">
        <div class="col-6 mt-3">
          {% if name.department %}
          <strong class="mr-2"> School:</strong><span class="text-primary font-weight-bolder">{{name.school}}</span> <br>
          <strong class="mr-2">GPA:</strong> <span class="text-primary mr-1">{{graduate.GPA}} </span> 
      
          <strong class="mr-2"> CGPA:</strong><span class="text-primary font-weight-bolder">{{graduate.CGPA}}</span> <br>
          <strong class="mr-2">Year:</strong> <span class="text-primary mr-1">{{name.department.year_required}} Year</span>
      
        {% else %}
       <strong class="mr-2"> School:</strong><span class="text-primary font-weight-bolder">Not Specified</span> <br>
       <strong class="mr-2">Year required:</strong> <span class="text-primary">?</span>
          {% endif %}
        </div>
        <div class="col-6">
        <img class="image float-right" src="{{name.profile.qr_code.url}}" alt="profile" height="120px"  >
      </div>
    </div>
      </div>
     
    </div>
 
  </div>
  
{% endblock %}