accounts/urls.py
from django.urls import path
from. import views


app_name ='accounts'
urlpatterns = [
    path('', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('404/', views.not_found, name='404'),

    
]

ehedvs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_users.urls')),
    path('accounts/', include('accounts.urls')),
    path('super_admin/', include('super_admin.urls')),
    path('registrar_admin/', include('registrar_admin.urls')),
    path('graduates/', include('graduates.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
     path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
      ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
          ),
          name='password_reset_confirm'),
     path('password-reset-complete/',
          auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

graduates/urls.py
from django.urls import path
from. import views
app_name ='graduates'
urlpatterns = [

    path('', views.index, name='home'),
    path('school/', views.student_update, name='school'),
    path('dept/<path:id>/', views.school_department, name='dept'),
    path('request_approved_checker', views.request_approved_checker, name='request_approved_checker'),
    path('upload/', views.student_upload, name='upload' ),
    path('academic/', views.acadamic_history, name='academic'),
    path('status/', views.student_status, name='status'),
    path('status_detail/<path:id>/', views.status_detail, name='status_detail'),
    path('certificate_generation/',views.certificate_generation, name='certificate_generation' ),
    path('profile/<path:pk>/',views.profile, name='profile' ),
    path('search/', views.search, name='search'),
    path('search_graduates/', views.search, name='search_graduates'),
    path('delete/<str:date>/', views.delete_records, name='delete'),
    path('student/', views.studentdata, name='student'),
    path('single/<path:id>/',views.single_certificate, name='single_certificate'),
    path('multi/', views.multiple_certificate, name='multi'),
    path('image_api/', views.get_profiles),
    path('image_api/<path:id>/', views.get_profile),
    path('student_api/', views.get_certificates),
    path('student_api/<path:id>/', views.get_certificate),
    
]

web_users/urls.py
from django.urls import path
from. import views
app_name ='web_users'
urlpatterns = [
    path('', views.web_user, name='index'),
    path('search/', views.certificate,  name='search'),


]

graduates/models.py
from typing import Tuple
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from super_admin.models import University
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw
from accounts.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save
from django.dispatch import receiver
from registrar_admin.models import Faculty, Program


#from ehedvs import settings


class Student(models.Model):
    institution = models.ForeignKey(
        University, on_delete=models.CASCADE, null=True)
    id = models.CharField(max_length=200, primary_key=True,
                          verbose_name='ID Number ')
    full_name = models.CharField(max_length=255, verbose_name='student name')
    gender = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField()
    registration_year = models.DateField(
        auto_now_add=True, null=True, verbose_name='Registration_Date')
    created_by = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL, null=True)
    school = models.ForeignKey(
        Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    department = models.ForeignKey(
        Program, on_delete=models.SET_NULL, null=True, blank=True)
    level_of_completion = models.FloatField(default=0.0, blank=True, null=True)

    class Meta:
        ordering = ['-registration_year']

    def __str__(self):
        return self.full_name


def academic_status_determiner(batch, semester, GPA, CGPA):
    if batch == 1 and semester == 1:
        if GPA >= 1.50 and CGPA >= 1.50:
            status = "Promoted"
        else:
            status = "Dismissed"
    elif batch == 1 and semester == 2:
        if GPA < 1.50 or CGPA < 1.75:
            status = "Dismissed"
        else:
            status = "Promoted"

    elif batch >=2:
        if GPA<1.50 or CGPA < 1.75:
            status = "Dismissed"
        else:
            status = "Promoted"


    
    else:
        status = "Dismissed"

    return status


class AcademicHistory(models.Model):
    sem = (
        ('1', '1st semester'),
        ('2', '2nd semester'),
    )
    status = (
        ('Promoted', 'Promoted'),
        ('Dismissed', 'Dismissed'),
        ('suspended', 'suspended')
    )
    batch = (
        ('1', '1st year'),
        ('2', '2nd year'),
        ('3', '3rd year'),
        ('4', '4th year'),
        ('5', '5th year'),
        ('6', '6th year'),
    )

    student = models.ForeignKey(Student,  on_delete=models.CASCADE)
    batch = models.CharField(
        max_length=20, choices=batch, verbose_name="Class Year")
    semester = models.CharField(max_length=20, choices=sem)
    GPA = models.FloatField(default=0.0)
    CGPA = models.FloatField(default=0.0)
    academic_status = models.CharField(
        max_length=20, choices=status, blank=True, null=True)
    uploaded_by = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL, null=True)
    uploaded_date = models.DateField(auto_now=True, verbose_name='Date')

    class Meta:
        ordering = ['-uploaded_date']

    def __str__(self):
        return "%s 's  %s year %s semester Academical status " % (self.student, self.batch, self.semester)


@receiver(pre_save, sender=AcademicHistory)
def accademical_status(sender, instance, *args, **kwargs):
    instance.academic_status = academic_status_determiner(
        instance.batch, instance.semester, instance.GPA, instance.CGPA)


class Profile(models.Model):
    student = models.OneToOneField(Student, on_delete=models.CASCADE)
    qr_code = models.ImageField(upload_to='qr_codes')
    image = models.ImageField(default='default.png', upload_to='student_image')

    def __str__(self):
        return f'{self.student} Profile'


# pre_save signal for generating  qr_code

@receiver(pre_save, sender=Profile)
def profile_pre_save(sender, instance, *args, **kwargs):
    if not instance.qr_code:
        qrcode_img = qrcode.make(instance.student.id)
        canvas = Image.new('RGB', (320, 320), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qr_code-{instance.student.id}.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        instance.qr_code.save(fname, File(buffer), save=False)
        canvas.close()



 

web_users/models.py
from django.db import models

# Create your models here.

graduates/views.py
import datetime
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.http import Http404
from .models import  Student, AcademicHistory, Profile
from .resources import StudentResource, AcademicalResource
from django.contrib import messages
from tablib import Dataset
from django.utils import timezone
from .forms import AcademicHistoryForm, ProfileUpdateForm, ExapleForm, update_dept,StudentForm
from django.utils import timezone
from .filter import AcademicFilter, StudentFilter
from datetime import date
from django.contrib.auth.decorators import login_required
from accounts.decorators import registrar_admin, registrar_staff, allowed_users
from accounts.models import RegistrarStaff, RegistrarAdmin, User
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import StudentSerializer, ProfileSerializer, CertificateSerializer
from super_admin import signals
from registrar_admin.models import Request
from django.forms.models import modelformset_factory
from registrar_admin.models import Faculty, Program

# -------------------------------
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from graduates import serializers


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def index(request):
    status = "pending"
    uni = RegistrarStaff.objects.get(user=request.user).university
    print(uni)
    r_admin = User.objects.get(registraradmin__university=uni)
    print(r_admin)
    if Request.objects.filter(sender=r_admin)[0:1]:
        sub = Request.objects.filter(sender=r_admin)[0:1].values('status')[0]
        status= sub['status']
    #--------------------------------------------------#
    status = "approved"                       
    #--------------------------------------------------#
    students = Student.objects.filter(created_by=request.user).count()
    profile_changed=None
    acadamic_historys = AcademicHistory.objects.filter(uploaded_by=request.user).count()
    profile = Profile.objects.filter(image='default.png', student__created_by=request.user ).count()
    if students:
        profile_changed =100-(profile/students)*100
    context = {
        'students': students,
        'acadamic_historys': acadamic_historys,
         'profile_changed':profile_changed,
        'profile': profile,
        'status':status
    }
    return render(request, 'graduates/home.html', context)

def student_update(request):
    user = request.user
    student = Student.objects.filter(created_by=user)
    StudentForm = update_dept(user)
    StudentFormset = modelformset_factory(Student, form=StudentForm, extra=0)
    formset = StudentFormset(request.POST or None, queryset=Student.objects.filter(
        created_by=user, school__isnull=True, department__isnull=True))
    
    if formset.is_valid():
        instances = formset.save(commit=False)
        for instance in instances:
            instance.save()

    context = {
        'formset': formset,
        'no_formset':len(formset.forms)
    }
    return render(request, 'graduates/school&dept_update.html', context)

def school_department(request, id):
    student = Student.objects.get(id=id)
    user = request.user
    if request.method == 'POST':
        form = StudentForm(user,request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('/graduates/student/')

    else:
        form = StudentForm(user,instance=student)
    context = {
        'form': form
    }
    return render(request, 'graduates/school_dept.html', context)




def request_approved_checker(request):
    status = "pending"
    uni = RegistrarStaff.objects.get(user = request.user).university
    admin = RegistrarAdmin.objects.get(university=uni)
    if Request.objects.filter(sender=admin)[0:1]:
        sub = Request.objects.filter(sender=admin)[0:1].values('status')[0]
        status= sub['status']
    return HttpResponse(status)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def graduates(request):
    year = ExapleForm()
    graduates = Student.objects.all().order_by('-uploaded_date')
    graduateFilter = StudentFilter(request.GET, queryset=graduates)
    graduates = graduateFilter.qs
    context = {'graduates': graduates,
               'graduateFilter': graduateFilter, 'year': year}
    return render(request, 'graduates/student_list.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def student_status(request):
    students = AcademicHistory.objects.filter(uploaded_by=request.user).order_by('-uploaded_date')
    myfilter = AcademicFilter(request.GET, queryset=students)
    students = myfilter.qs
    deletion_number = students.count()
    if request.method == 'POST':
        students.delete()
        return redirect('/graduates/status/')
    context = {'students': students, 'myfilter': myfilter,
      'deletion_number': deletion_number}
    return render(request, 'graduates/student_status.html', context)



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def file_upload(request):
    return render(request, 'graduates/file_upload.html')


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def status_detail(request, id):
    #student_i = Student.objects.get(id=id)
    #name = AcadamicHistory.objects.get(student=student_id).student.first
    name = Student.objects.get(id=id)
    student = AcademicHistory.objects.filter(student=id)
    context = {'students': student, 'name': name}
    return render(request, 'graduates/status_detail.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def registrar_staff(request):
    students = Student.objects.all().count()
    context = {'students': students}
    return render(request, 'graduates/registrar_staff.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def search(request):
    if request.GET:
        search_term = request.GET['date']
        num = Student.objects.filter(registration_year=search_term).count()

    context = {
        'search_term': search_term,
        'num': num

    }
    return render(request, 'graduates/delete_students.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def delete_records(request, date):

    if request.method == 'POST':
        num = Student.objects.filter(registration_year=date, created_by=request.user)
        if num:
            num.delete()
            messages.success(request, "successfully deleted")
            return redirect('/graduates/student')
        else:
            messages.warning(
                request, 'No records found with this selected dateeeee')
            return redirect('/graduates/student')

    return render(request, 'graduates/delete_students.html')



@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def student_upload(request):
    try:
         if request.method == 'POST':
            student_resource = StudentResource()
            dataset = Dataset()
            new_student = request.FILES['myfile']
            imported_data = dataset.load(new_student.read(), format='xlsx')
            # logged_user
            user = request.user.id
            unv = RegistrarStaff.objects.get(user_id=user).university_id
            created_by = request.user.id
            registration_year = datetime.date.today()

            result = student_resource.import_data(
                dataset,
                dry_run=True,
                raise_errors=True,
                institution=unv,
                created_by=created_by,
                reg_year=registration_year
            )
            if result.has_errors():
                messages.error(request, 'Uh oh! Something went wrong....')

            else:
                student_resource.import_data(
                    dataset,
                    dry_run=False,
                    institution=unv,
                    created_by=created_by,
                    reg_year=registration_year
                )
                messages.success(
                    request, 'You have uploaded the file  successfully!')
                return redirect('/graduates/student')

    except Exception as e:
       messages.error(request, e)
       return redirect('/graduates/')
   
    return render(request, 'graduates/upload.html')


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['registrar_staff'])
def acadamic_history(request):
    try:
        if request.method == 'POST':
            student_resource = AcademicalResource()
            dataset = Dataset()
            new_student = request.FILES['myfile']
            imported_data = dataset.load(new_student.read(), format='xlsx')
            now = datetime.date.today()
            uploaded_by = request.user.id

            result = student_resource.import_data(
                dataset,
                dry_run=True,
                raise_errors=True,
                uploaded_by=uploaded_by,
                uploaded_date=now
            )
            if result.has_errors():
                messages.error(request, 'Uh oh! Something went wrong....')

            else:
                student_resource.import_data(
                    dataset,
                    dry_run=False,
                    uploaded_by=uploaded_by,
                    uploaded_date=now
                )
                messages.success(request, 'You have uploaded successfully!')
                return redirect('/graduates/')

    except Exception as e:
        messages.error(request, e)
        return redirect('/graduates/')
   

templates/graduates/certificate_generation.html
{% extends 'graduates/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block subtitle %}Certificate Generation{% endblock %}
{% block first %}Home {% endblock %}
{% block second %}Certificate{% endblock %}
{% block content%}
<!-- /.card -->
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header border-0">
              <h3 class="card-title mb-1"> <i class="fa fa-print text-orange mr-1"></i>
              <span style=" font-style: oblique; ,font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">Certificate</span></h3>
              <div class="card-tools">
                <a >
                <i class="fas fa-barcode  text-indigo" ></i>
                </a>
              </div>
            </div>
            <div class="card-body table-responsive p-3">
              <table class="table table-striped table-valign-middle certificate table-borderless">
                <thead>
                <tr>
                  <th>Image</th>
                  <th>Student</th>
                  <th>ID</th>
                  <th>Batch</th>
                  <th class=" text-center text-info">Competion Level</th>
                  <th>Generate Certificate</th>
                  <th>More</th>
        
                </tr>
                </thead>
                <tbody>
                    {% for certificate in certificates %}
                <tr>
                  <td>
                    <img src="{{certificate.profile.image.url}}" alt="student image" class="img-circle img-size-32 mr-2">
                  </td>
                  <td>{{certificate}}</td>
                  <td>{{certificate.id}}</td>
                  <td>
                    <small class="text-success mr-1">
                      
                   {{certificate.registration_year.year}}
                  </td>
                  <td class="text-center">
                    {% if certificate.level_of_completion == 0.0 %}
                    <p class="text-info ">unpredictable</p>
                    {% else %}
                    {{certificate.level_of_completion|floatformat:2 }}
                    <span class="text-info"><sup>%</sup></span>
                    {% endif %}
                  
                </td>
                  <td>
                    {% if certificate.level_of_completion >= 100 %}
                    <a  href="{% url 'graduates:single_certificate' certificate.id %}" class="text-muted text-center " disable>
                      <i class="fas fa-file-download ml-4 text-orange btn-sm mr-5"></i>
                       
                    </a>
                    {% else %}
                    <button class="btn btn-sm" disabled><i class="fas fa-file-download ml-4 text-orange mr-5"></i></button>
                    {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'graduates:status_detail' certificate.id %}"><i class="fa fa-angle-double-right"></i></a>
                  </td>
                 
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
    </div>
   <!--
    <div class="col-md-3">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i  class="fa fa-id-card-alt text-indigo mr-1"></i>
              <span class="font-italic">Generate multiple certificate</span>
            </h3>
          </div>
         
          <div class="card-body">
            <p>YET TO COME</p>
          </div>
          
        </div>
      
      </div>

-->

</div>

 
 <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
 <!-- Bootstrap 4 -->
 <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
 <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
 
 <!-- e-HEDVS App -->
 <script src=" {% static 'dist/js/e-hedvs.min.js' %}"></script>
 <script>
     $('.certificate').DataTable({
          ordering:false,
         lengthMenu:[[5,10,15,50,-1],[5,10,15,50,"All"]],
        
     });
 </script>
 
  
{% endblock%}

templates/graduates/delete_graduates.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-HEDVS|delete</title>
    <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/e-hedvs.min.css ' %}">
    


</head>
<body>
  {% if num == 0 %}
  <div class="container mt-4 ">
     <div class="row ">
         <div class="col-4 shadow-sm p-2 ">
            <h6>No records found with selected <span class="text-warning">date</span></h6> 
            <a href="{% url 'graduates:student' %}" > go back</a>
         </div>
     </div>
    
  </div>
  
  
  <!-- Modal -->
  
    
    {% else %}

    <div class="container mt-4">
        <h5>Are you sure you want to delete multiple records and related data ?</h5>
             <ul>
                 <li><strong>Graduates: {{num}}</strong></li>
             </ul>
        
        <form action="{% url 'graduates:delete' search_term %}" method="POST" >
            {% csrf_token %}
            <a href="{% url 'graduates:student' %}" class="btn btn-lg btn-info ml-2">Cancel</a>
            <input type="submit" name='delete' value="Yes" class="btn btn-lg btn-danger ">
    
        </form>
     </div> 

     {% endif %}
             
            
                
                
            
                
   
    <!-- REQUIRED SCRIPTS -->



<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ehedvs App -->
<script src=" {% static 'dist/js/e-hedvs.min.js' %}"></script>

</body>
</html>

templates/graduates/delete_students.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-HEDVS|delete</title>
    <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/e-hedvs.min.css ' %}">
    


</head>
<body>
  {% if num == 0 %}
  <div class="container mt-4 ">
     <div class="row ">
         <div class="col-4 shadow-sm p-2 ">
            <h6>No records found with selected <span class="text-warning">date</span></h6> 
            <a href="{% url 'graduates:student' %}" > go back</a>
         </div>
     </div>
    
  </div>
  
  
  <!-- Modal -->
  
    
    {% else %}

    <div class="card-body ml-5 mt-3">
        <div class="row ">
         <div class="col-md-7">
        <div class="card card-danger card-outline direct-chat direct-chat-success shadow-sm">
          <div class="card-header">
            <h3 class="card-title text-danger">Dangerous Operation</h3>
  
            <div class="card-tools">
              <i class="fa fa-question-circle"></i>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-5">
            <div class="container mt-4">
                <h5>Are you sure you want to delete multiple records and related data ?</h5>
                     <ul style="list-style: none;">
                         <li><strong>Students: {{num}}</strong></li>
                         <li><strong>Profile: ?</strong></li>
                         <li><strong>Academic Status: ?</strong></li>
                     </ul>
                
                <form action="{% url 'graduates:delete' search_term %}" method="POST" >
                    {% csrf_token %}
                    <a href="{% url 'graduates:student' %}" class="btn btn-lg btn-info ml-2">Cancel</a>
                    <input type="submit" name='delete' value="Yes" class="btn btn-lg btn-danger ">
            
                </form>
             </div> 
           
          </div>
          
        </div>
        <!--/.direct-chat -->
      </div>
      </div>
      </div>
    

    

     {% endif %}
             
            
                
                
            
                
   
    <!-- REQUIRED SCRIPTS -->



<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ehedvs App -->
<script src=" {% static 'dist/js/e-hedvs.min.js' %}"></script>

</body>
</html>

templates/graduates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4 ">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'dist/img/ehedvs.jpg' %}"
       alt="e-HECAS Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light"><b class="text-primary">e</b>-HEDVS</span>
     </a>
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{request.user.image.url}}" class="img-circle elevation-2 bg-success" alt="User Image">
        </div>
        <div class="info text-capitalize">
          <a href="#" class="d-block"> {{request.user}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
       
          <li class="nav-item">
            <a href="{% url 'graduates:home' %}" class="nav-link {% block active %}{% endblock %}">
                <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li> 
          <li class="nav-item">
            <a href="{% url 'graduates:student' %}" class="nav-link ">
              <i class="nav-icon fa fa-user-graduate "></i>
              <p>
               Student Registry
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            <a href="{% url 'graduates:status' %}" class="nav-link ">
              <i class="nav-icon fa fa-history "></i>
              <p>
                Academical Status
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'graduates:school' %}" class="nav-link ">
              <i class="nav-icon fa fa-user-edit "></i>
              <p>
                Update Department
              </p>
            </a>
          </li>

          <li class="nav-item ">
            <a href="{% url 'graduates:certificate_generation' %}" class="nav-link ">
              <i class="nav-icon fa fa-stamp "></i>
              <p>
              Generate Certificate
              </p>
            </a>
          </li>
         
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>